---

- name: Ensure jenkins user
  user:
    name: '{{ jenkins_username }}'
    password: '{{ jenkins_password }}'
    shell: /bin/bash
    groups: '{{ jenkins_user_groups }}'
    state: present

- name: Build home
  file: 
    path: '{{ jenkins_home }}'
    owner: '{{ jenkins_username }}'
    group: '{{ jenkins_username }}'
    mode: 0700
    state: directory

- name: Add master public key to authorized keys
  authorized_key:
    user: '{{ jenkins_username }}'
    key: '{{ jenkins_authorized_key }}'


